### ISSUE TITLE
履歴の複数削除機能がほしい

### ISSUE THREAD

**Issue by funa-tk** [DeNA/PacketProxy#11]
現在は1個ずつもしくは、全部を削除することしかできない

**Comment by DoranekoSystems** [comment]
![packet](https://user-images.githubusercontent.com/56913432/85854333-2be95480-b7ef-11ea-9aac-ba2283bdbca0.png)

1.履歴を複数選択可能にする。
2.一番上を基本選択項目にし、二個目以降を副選択項目にして色を分ける。
3.delete select itemsの項目を追加する。

上のような実装でよければpr投げさせていただきます。

**Comment by funa-tk** [comment]
良さそうです！
PRお待ちしております！

**Comment by funa-tk** [comment]
209854b
で実装されたのでclose
