### ISSUE TITLE
macOS用のインストーラーアプリケーションが署名されていない

### ISSUE THREAD

**Issue by kenchan0130** [DeNA/PacketProxy#29]
## 期待している動作

`PacketProxy-x.x.x-Installer-Mac.app` を実行してもGatekeeperにブロックされないこと。

## 実際の動作

`PacketProxy-x.x.x-Installer-Mac.app` を実行すると以下のようにGatekeeperにブロックされる
<img width="421" alt="スクリーンショット 2019-10-02 13 20 36" src="https://user-images.githubusercontent.com/1155067/66017853-71564b00-e517-11e9-97f8-9cd55df3a8ca.png">

組織や企業において、Gatekeeperを有効にすることはセキュリティ上有効な手段であり、推奨される行為です。
しかし、このアプリケーションのインストーラーは開発者署名がされておらず、改ざんされている可能性があると捉えられてもおかしくないと私は考えています。

## 再現方法

1. https://github.com/DeNA/PacketProxy/releases/download/1.0.0/PacketProxy-1.0.0-Installer-Mac.zip から zip をダウンロード
2. zip を解凍
3. `PacketProxy-1.0.0-Installer-Mac.app` をFinder上でダブルクリック

**Comment by funa-tk** [comment]
ありがとうございます。たしかに私も署名が入っていたほうが良いと思いますので、やり方等ちょっと考えさせてください。

署名版がご用意できるまで、もしセキュリティ的に気になるようであれば、PacketProxyはオープンソースですので、ソースコードをダウンロードしていただき安全性をチェックした上でご自身でビルドしていただくと、より安全であると確証が得られると思います！

ところで、現在DeNA/PacketProxyのリリースページにバイナリをアップロードできる人を制限しておりますので、リリースページから直接ダウンロードしていただく限り、完全ではないのですが一定の安全性はあると考えてもらっても良いと思っています。

**Comment by kenchan0130** [comment]
> たしかに私も署名が入っていたほうが良いと思いますので、やり方等ちょっと考えさせてください。

こちらに関してですが、macOSのappに関しては一般的に取られる方法は以下のとおりです。

1. `.app` を署名して、zipなど圧縮して配布
2. `.app` を署名して、disk image にして配布
3. `.app`  を署名して、pkg にしてpkgにも署名して配布

以下は個人的な意見ですが、izpackを使用してインストーラーを作らずに `PacketProxy.app` を上記の様にして配布するだけにしても良いかもしれません。
[jpackager](https://jdk.java.net/jpackage/) を使用するといい感じに app 化できるかもしれません。

参考: https://github.com/yusuke/shogun/blob/master/pom.xml

**Comment by funa-tk** [comment]
ありがとうございます！

**Comment by funa-tk** [comment]
`.app` にcodesignコマンドで署名をしてみたのですが、`code object is not signed at all` というエラーになり何も起きないですね・・。`.app` ディレクトリの中にMach-Oバイナリが含まれていない（jarファイルがあるだけ）のが原因かもしれません。

`.dmg` の場合は署名できるようなので、`.dmg` の形で署名して配布するのが正解なのかもしれません。
jpackager を使うと、dmgを生成して署名もしてくれるらしいので、それを使うのがいいのかも。

**Comment by kenchan0130** [comment]
dmg を署名したところで、`.app` のバイナリ自体が署名されていないと、app起動時に結局同じようにGatekeeperのブロックされます。具体的には `app/Contents/MacOS/APP_BINARY_NAME` が署名されていないためです。

故に、jpackager で作成する(shogun app のように)エントリーポイントとなるMach-Oバイナリを用意しておくのが良いと思われます。

**Comment by funa-tk** [comment]
> エントリーポイントとなるMach-Oバイナリを用意しておくのが良いと思われます。
それが良さそうですね！

ところで、dmgが署名済みなのに、dmgの中にある.appを信頼しないappleの仕様に違和感を覚えますね

**Comment by kenchan0130** [comment]
> dmgが署名済みなのに、dmgの中にある.appを信頼しないappleの仕様に違和感を覚えますね

こちらは歴史的経緯がありますが、

- https://developer.apple.com/documentation/xcode/notarizing_your_app_before_distribution
- https://stackoverflow.com/questions/53112078/how-to-upload-dmg-file-for-notarization-in-xcode

このあたりが参考になるかと思います。

**Comment by funa-tk** [comment]
なるほど！ありがとうございます。

**Comment by funa-tk** [comment]
javapackagerを利用してOpenJDK8を内包した上で.appを生成し、署名してAppleの
公証(notary)を受けました。

`PacketProxy-1.0.2-Installer-Mac-Singed.dmg` という名前で、[リリースページ](https://github.com/DeNA/PacketProxy/releases)に置きました。
手元では、GateKeeperに弾かれないことを確認済みです。
他ユーザの確認が取れたら、このチケットをクローズします。

**Comment by kenchan0130** [comment]
@funa-tk 
私個人の環境に関してですが、
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
```
こちらの環境で、署名されており、GateKeeperを通過したことを確認しました。

対応ありがとうございます！

**Comment by funa-tk** [comment]
kenchan0130さん、ご確認ありがとうございました！
チケットクローズします。
