### ISSUE TITLE
ローカル保存時に拡張子がついた結果上書きされる場合に確認メッセージが出ない

### ISSUE THREAD

**Issue by cos65535** [DeNA/PacketProxy#31]
ローカル保存(sqlite3) で hoeg.sqlite3 のファイルが既にある時にhogeで保存しようとすると、上書き保存の確認メッセージが出ない。
ローカル保存(txt)も同様。

**Comment by prprhyt** [comment]
ついでにJFilerChooserまわりもリファクタリング済みです。
