### ISSUE TITLE
文字エンコーディングを指定できるようにする

### ISSUE THREAD

**Issue by funa-tk** [DeNA/PacketProxy#32]
パケットデータの表示エリアは、現在のところUTF-8固定で表示されるようになっている。他のエンコーディングでも表示できるように選択できれば便利

**Comment by prprhyt** [comment]
ac9e3b90fc74d61d4910a04b96d1398e38f5bc96
文字コードの選択機能を追加しました。
今の所、文字コードは"UTF-8", "Shift_JIS", "x-euc-jp-linux", "ISO-2022-JP", "ISO-8859-1"
が選択可能です。
そのうち、ユーザがオプションから任意の文字コードを追加できるようにもしたいと思います。

**Comment by prprhyt** [comment]
設定画面追加しました。
b9ea73741bffa3e6319e1a2c4015bef8cf2d3e05
