### ISSUE TITLE
Question on how to set up DNS overwrite

### ISSUE THREAD

**Issue by jpopxfile** [DeNA/PacketProxy#51]
Hello,

I am trying to use the gRPC module, but before even using that, I was trying to set up the Forwarding but am still not able to set up the DNS overwrite as documented here.

https://github.com/DeNA/PacketProxy/wiki/Using-PacketProxy#Forwarding-with-DNS-Overwrite

I have tried to set up exactly the same as the wiki

![Screenshot from 2019-11-19 14-46-48](https://user-images.githubusercontent.com/9736802/69119954-76795480-0adb-11ea-9e4b-1d641a710b73.png)

![Screenshot from 2019-11-19 14-15-43](https://user-images.githubusercontent.com/9736802/69118539-31ebba00-0ad7-11ea-9470-96f23557df46.png)

However, when I try to start the private DNS server, I get the following error

`2019/11/19 14:50:53       cannot boot private DNS server (permission issue or already listened)`

Hope you can help me with figuring out what I am doing wrong. Thanks.

**Comment by funa-tk** [comment]
If you use Linux, you need a root privilege to open the port 443 (and all the ports less than 1024).
Could you try `sudo java -jar build/libs/PacketProxy.jar` to boot PacketProxy as root?
If you use latest mac or windows, you need not boot PacketProxy as root. On mac/windows, a normal user can obtain root privilege after booting application through a dialog like the below.
![スクリーンショット 2019-11-19 15 41 53](https://user-images.githubusercontent.com/1781263/69122845-2e5e3000-0ae3-11ea-88e0-9970aa439a98.png)

**Comment by jpopxfile** [comment]
On Linux, I managed to run as root and enable listen port 443. However I cannot enable the private DNS server. 
Similarly, on OSX, no issue with port 443, only problem with the DNS server. I have enabled accepting incoming network connections in the firewall.

**Comment by funa-tk** [comment]
Any other application is already listening on port UDP/53.
Could you check the port with `sudo netstat -uln`?

**Comment by funa-tk** [comment]
I frequently use `dig @localhost example.com. a` command to check if the private DNS server successfully works.

**Comment by jpopxfile** [comment]
Seems like mDNSResponder is listening on OSX, can't seem to kill it though since it keeps coming back.

On Linux, I managed to kill dnsmasq.

**Comment by funa-tk** [comment]
I found a good document blow about 'mDNSResponder' and port conflict.
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-macOS
According to the above document, port conflict is caused by the following conditions:
> mDNSResponder listens to port 53 when applications using the native hypervisor run. Docker is an example of an application using this.
> mDNSResponser also listens to port 53 when Internet sharing has been enabled.

I've never used hypervisor nor Internet sharing, so the DNS server works on my mac.

**Comment by funa-tk** [comment]
Thank you for the solution! By the way, I also sometimes use pfctl to forward packets to packetproxy. pfctl is a good tool!

**Comment by jpopxfile** [comment]
Disabling internet sharing solved the problem! Thanks.

Anyway, I managed to get an app that is using gRPC to go through the SSL_TRANSPARENT_PROXY, but got a `javax.net.ssl.SSLException: Socket Closed` error

In the history, it looks like this:

<img width="1223" alt="Screen Shot 2019-11-19 at 17 34 15" src="https://user-images.githubusercontent.com/9736802/69130155-62415180-0af3-11ea-90be-ba4e2ea99600.png">

<img width="1166" alt="Screen Shot 2019-11-19 at 17 40 28" src="https://user-images.githubusercontent.com/9736802/69130403-ce23ba00-0af3-11ea-8d7d-f5c703d79c4f.png">

I wonder what the issue is.

**Comment by funa-tk** [comment]
Your configuration looks good to me. But unfortunately gRPC use HTTP2 protocol and current PacketProxy doesn't support HTTP/2...
`PRI * HTTP/2.0 brah brah` in the image you attached is just HTTP2 data.
I am developing HTTP2 functionality now. It takes a few weeks to finish.
After HTTP2 support, gRPC will work!

**Comment by jpopxfile** [comment]
Thank you for taking the time to answer all my questions!
