### ISSUE TITLE
gRPCのALPNでのネゴシエーションでgrpc-expが使われないケースがある

### ISSUE THREAD

**Issue by prprhyt** [DeNA/PacketProxy#61]
一部のライブラリでALPN over TLSでのgRPCのネゴシエーションに使われていた
`grpc-exp`を廃止して，代りに通常のHTTP/2と同じ`h2`を
ALPNのnext-protocol-versionsに指定しているケースがあるようです．
grpc-javaでは1/10付のコミットでgrpc-expを使わないように修正されていました．
https://github.com/grpc/grpc-java/issues/6591
https://github.com/grpc/grpc-java/pull/6592

75df14c3f03345626188b5710e713f11320b65bc のPacketProxyが
ALPNで`h2`のみを使うようになった最新版( https://github.com/grpc/grpc-java/commit/258fe12f0281e96f76d36cda6cbffeb6476e65d7 )のgrpc-javaのクライアント/サーバーでは動作しないことを確認しました．

**Comment by funa-tk** [comment]
masterにマージしたのでcloseします。
