### ISSUE TITLE
forwarder先に指定されていたhostを削除した際に、設定ファイルに不整合が生じる

### ISSUE THREAD

**Issue by ryoissy** [DeNA/PacketProxy#85]
forwarder先に指定されていたhostをServersの一覧から削除すると、listen portのforwarder先が何も設定されてない状態になってしまいます。
そのため、設定ファイルに不整合が生じて、ローカルに設定ファイルが保存できなくなるなどのエラーが発生してしまいます。

**Comment by funa-tk** [comment]
修正されたのでクローズします
